services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./src/backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_db
      POSTGRES_HOST: db
    volumes:
      - ./src/backend/:/src/backend

  interface:
    build: ./src/interface
    container_name: interface
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  postgres_data:
